/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Capotes
 */
public class TestDeConsola extends javax.swing.JFrame {

    /**
     * Creates new form TestDeConsola
     */
    public TestDeConsola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        buscarAlum = new javax.swing.JMenuItem();
        gestionAlum = new javax.swing.JMenuItem();
        menuMateria = new javax.swing.JMenu();
        formMateria = new javax.swing.JMenuItem();
        buscarMate = new javax.swing.JMenuItem();
        menuInscripcion = new javax.swing.JMenu();
        VistaInscripcion = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuAlumno.setText("Alumno");

        buscarAlum.setText("Buscar Alumno");
        buscarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlumActionPerformed(evt);
            }
        });
        menuAlumno.add(buscarAlum);

        gestionAlum.setText("Gestion Alumno");
        gestionAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionAlumActionPerformed(evt);
            }
        });
        menuAlumno.add(gestionAlum);

        jMenuBar1.add(menuAlumno);

        menuMateria.setText("Materia");

        formMateria.setText("Formulario Materia");
        formMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formMateriaActionPerformed(evt);
            }
        });
        menuMateria.add(formMateria);

        buscarMate.setText("Buscar Materia");
        buscarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMateActionPerformed(evt);
            }
        });
        menuMateria.add(buscarMate);

        jMenuBar1.add(menuMateria);

        menuInscripcion.setText("Inscripcion");

        VistaInscripcion.setText("Formulario Inscripcion");
        VistaInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaInscripcionActionPerformed(evt);
            }
        });
        menuInscripcion.add(VistaInscripcion);

        jMenuItem2.setText("Cargar Notas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuInscripcion.add(jMenuItem2);

        jMenuItem3.setText("Lista De inscripciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuInscripcion.add(jMenuItem3);

        jMenuBar1.add(menuInscripcion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlumActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        BuscarAlumno alum  = new BuscarAlumno();
        Escritorio.add(alum);
        alum.setVisible(true);
        Escritorio.moveToFront(alum);
        
       
    }//GEN-LAST:event_buscarAlumActionPerformed

    private void gestionAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionAlumActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaAlumno alum  = new VistaAlumno();
        Escritorio.add(alum);
        alum.setVisible(true);
        Escritorio.moveToFront(alum);
      

    }//GEN-LAST:event_gestionAlumActionPerformed

    private void buscarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMateActionPerformed
        
        Escritorio.removeAll();
        Escritorio.repaint();
        BuscarMateria mate =new BuscarMateria();
        Escritorio.add(mate);
        mate.setVisible(true);
        Escritorio.moveToFront(mate);
   
    }//GEN-LAST:event_buscarMateActionPerformed

    private void formMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formMateriaActionPerformed
     
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaMateria mate =new VistaMateria();
        Escritorio.add(mate);
        mate.setVisible(true);
        Escritorio.moveToFront(mate);
    }//GEN-LAST:event_formMateriaActionPerformed

    private void VistaInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaInscripcionActionPerformed
      
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaInscripcion ins =new VistaInscripcion();
        Escritorio.add(ins);
        ins.setVisible(true);
        Escritorio.moveToFront(ins);
    }//GEN-LAST:event_VistaInscripcionActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaCargarNota nota =new VistaCargarNota();
        Escritorio.add(nota);
        nota.setVisible(true);
        Escritorio.moveToFront(nota);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaListarInscripciones list =new VistaListarInscripciones();
        Escritorio.add(list);
        list.setVisible(true);
        Escritorio.moveToFront(list);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestDeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestDeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestDeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestDeConsola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestDeConsola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem VistaInscripcion;
    private javax.swing.JMenuItem buscarAlum;
    private javax.swing.JMenuItem buscarMate;
    private javax.swing.JMenuItem formMateria;
    private javax.swing.JMenuItem gestionAlum;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenu menuInscripcion;
    private javax.swing.JMenu menuMateria;
    // End of variables declaration//GEN-END:variables
}
