/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Alumno;
import Modelo.Conexion;
import Modelo.Inscripcion;
import Modelo.Materia;
import Persistencia.AlumnoData;
import Persistencia.InscripcionData;
import Persistencia.MateriaData;
import java.sql.Connection;

/**
 *
 * @author Sutara
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class VistaInscripcion extends javax.swing.JInternalFrame {
    
    private Conexion con = new Conexion("jdbc:mariadb://localhost:3306/grupogp5universidad", "root","");
    private ArrayList <Alumno> listaAlumnos;
    private ArrayList<Materia> listaMateria;
    
    private AlumnoData alumdata ;
    private MateriaData matedata;
    private InscripcionData inscrData;
    private DefaultTableModel modelo;
    
    public VistaInscripcion() {
        this.alumdata= new AlumnoData(con);
        this.matedata = new MateriaData(con);
        this.inscrData = new InscripcionData(con);
        modelo = new DefaultTableModel();
        
        this.listaAlumnos = alumdata.listarAlumnos();
        this.listaMateria = matedata.selectTodo();
        initComponents();
        
      
        cargarCabecera();
        cargarAlumnos();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInscribir = new javax.swing.JButton();
        btnAnular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumnos = new javax.swing.JComboBox<>();
        rbMateInscriptas = new javax.swing.JRadioButton();
        rbmateNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();

        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnAnular.setText("Anular Inscripcion");
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Formulario Inscripcion");

        jLabel2.setText("Seleccione un alumno:");

        rbMateInscriptas.setText("Materias inscriptas");
        rbMateInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMateInscriptasActionPerformed(evt);
            }
        });

        rbmateNoInscriptas.setText("Materias no inscriptas");
        rbmateNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmateNoInscriptasActionPerformed(evt);
            }
        });

        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jtabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInscribir)
                                .addGap(86, 86, 86)
                                .addComponent(btnAnular)
                                .addGap(88, 88, 88)
                                .addComponent(btnSalir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMateInscriptas, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(rbmateNoInscriptas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbmateNoInscriptas)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInscribir)
                            .addComponent(btnAnular)
                            .addComponent(btnSalir)))
                    .addComponent(rbMateInscriptas))
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rbMateInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMateInscriptasActionPerformed
        borrarFilaColumnas();
        // esto se hace para que este desmarcado el radio
            rbmateNoInscriptas.setSelected(false);
        Alumno alu = (Alumno) jcbAlumnos.getSelectedItem();
        
        ArrayList <Materia> lis = inscrData.mostrarMateriasInscriptas(alu.getIdAlumno());
        
         for (Materia mat : lis) {
        
        String estadoTexto = mat.isEstado() ? "Activo" : "Inactivo"; 
        
        modelo.addRow(new Object[] {
            mat.getIdMateria(),
            mat.getNombre(),
            mat.getAnio(),
            estadoTexto 
        });
        
    }
        btnInscribir.setEnabled(false);
        btnAnular.setEnabled(true);
    }//GEN-LAST:event_rbMateInscriptasActionPerformed

    private void rbmateNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmateNoInscriptasActionPerformed
         borrarFilaColumnas();
        rbMateInscriptas.setSelected(false);
        
        Alumno alu = (Alumno) jcbAlumnos.getSelectedItem();
        
        ArrayList<Materia> lista = inscrData.mostrarMateriasNOInscriptas(alu.getIdAlumno());
        
        for (Materia mat : lista) {
        
        String estadoTexto = mat.isEstado() ? "Activo" : "Inactivo"; 
        
        modelo.addRow(new Object[] {
            mat.getIdMateria(),
            mat.getNombre(),
            mat.getAnio(),
            estadoTexto 
        });
        
        }
        btnInscribir.setEnabled(true);
        btnAnular.setEnabled(false);
    }//GEN-LAST:event_rbmateNoInscriptasActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
       int fila = jtabel.getSelectedRow();
       if(fila != -1 ){
           
           Alumno alu = (Alumno)jcbAlumnos.getSelectedItem();
           
           int idMateria = (Integer)modelo.getValueAt(fila, 0);
           int idAlumno= alu.getIdAlumno();
           Inscripcion i = new Inscripcion(0,idAlumno,idMateria);
           
                     
          
          
           
           inscrData.inscripcion(i);
           borrarFilaColumnas();
           
           
       }
       
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
            int filaSeleccionada = jtabel.getSelectedRow();
            
            if( filaSeleccionada != -1){
                Alumno alum = (Alumno) jcbAlumnos.getSelectedItem();
                int idMateria= (int) modelo.getValueAt(filaSeleccionada, 0);
                int idAlumno= alum.getIdAlumno();
                inscrData.eliminarInscripcion(idAlumno, idMateria);
                borrarFilaColumnas();
            
            }else{
                JOptionPane.showMessageDialog(this, "Debe seleccionar una materia");
            }
    }//GEN-LAST:event_btnAnularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Alumno> jcbAlumnos;
    private javax.swing.JTable jtabel;
    private javax.swing.JRadioButton rbMateInscriptas;
    private javax.swing.JRadioButton rbmateNoInscriptas;
    // End of variables declaration//GEN-END:variables

    
    public void cargarCabecera(){
        
        modelo.addColumn("Id Materia");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
     
        
        jtabel.setModel(modelo);
        
    }

    public void cargarAlumnos(){
        
        for (Alumno alum : listaAlumnos) {
            jcbAlumnos.addItem(alum);
        }
    
    }
    
    public void borrarFilaColumnas(){
         int indice = modelo.getRowCount()-1;
            for(int i=indice; i>=0 ;i --){
                 modelo.removeRow(i);
                     }
    }


}
